.circleci/config.yml
Fix typo in the deploy command.
=> Fix CircleCI deploy

.circleci/config.yml
Fix bad indentation in CircleCI configuration file.
=> Fix bad indentation

.circleci/config.yml
Adds Makefile to CircleCI workspace.
=> Fix CircleCI workspace

ryr-docs/docs/how-to/setup-full-environment.md, ryr-docs/mkdocs.yml
Creates a setup guide which explains how to create the required
developer accounts as well as how to start the services to run the
request yo racks application.
Fixes: https://github.com/request-yo-racks/docs/issues/15
=> Create a setup howto

requirements/_base.txt, ryr-docs/docs/how-to/setup-full-environment.md, ryr-docs/mkdocs.yml
This replaces the default theme by the amazing material design theme
from [squidfunk](https://github.com/squidfunk/mkdocs-material).
Some markdown extensions where also added/enabled to improve the reading
experience.
Fixes: https://github.com/request-yo-racks/docs/issues/16
=> Replace the default theme

ryr-docs/docs/guides/setup-full-environment.md
Adds information about obtaining and using a GoogleMaps API key
"secretly" for the web project.
=> Add GoogleMaps element information

ryr-docs/docs/contributor-zone/adw-2017.md, ryr-docs/mkdocs.yml
The new collaborators ask to see the notes from the Austin Design Week
2017.
=> Add notefrom ADW 2017

ryr-docs/docs/contributor-zone/adw-2017.md
The bullet point layout for the ADW 2017 was incorrect.
=> Fix layout

ryr-docs/docs/contributor-zone/adw-2017.md
Fix multi-level bullet point lists.
=> Fix bullet points

ryr-docs/docs/guides/setup-full-environment.md, ryr-docs/mkdocs.yml
Adds a section which explains which software should be install on a
laptop/computer in order to start working on RYR.
Drive-by:
* Use tabs
=> Add pre-requisites section

ryr-docs/docs/guides/setup-full-environment.md
=> Reorganize the Setup guide

ryr-docs/docs/guides/setup-full-environment.md
Update the setup guide to show instructions for minikube only.
=> Update setup guide

ryr-docs/docs/guides/setup-full-environment.md
* Fixes the API test link
* Improve the script to create the `config.js` file
Fixes request-yo-racks/infra#21
=> Update the documentation

ryr-docs/docs/guides/setup-full-environment.md
Updates the documentation to reflect the latest changes in the setup of
the web project.
=> Update ryr config section

ryr-docs/docs/guides/setup-full-environment.md
Improves the setup guide based on feedback from new members.
=> Improve setup guide

ryr-docs/docs/guides/setup-full-environment.md
The script was modified to include a pull request if clone fails
Fixes #https://github.com/request-yo-racks/infra/issues/28
=> Update script to either clone or update the projects

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds the new RYR Github templates to the project.
=> Add new Github templates

ryr-docs/docs/guides/setup-full-environment.md
Updates the cloning scripts to automatically add the upstream remote.
Fixes request-yo-racks/docs#53
=> Update cloning script

ryr-docs/docs/guides/setup-full-environment.md
…clone/update script
- New feature (non-breaking change which adds functionality)
Description
-----------
Added "2> /dev/null" to the clone/update script in order to avoid seeing unnecessary error messages. 
It improves user experience.
It has been tested running the script against my local repository
Checklist:
----------
-  [x] I have updated the documentation accordingly
Fixes https://github.com/request-yo-racks/docs/issues/55
=> Redirect sterr messages to /dev/null in clone/update script 

ryr-docs/docs/guides/setup-full-environment.md
The environment variables in the bootstrap scripts have been rename for
consistency purpose. This patch reflects the change.
Description
-----------
Checklist:
----------
=> Update bootstrap script instructions

.circleci/config.yml
- Bug fix (non-breaking change which fixes an issue)
Description
-----------
We are facing some issue with the cache restoration mechanism on
CircleCI, therefore I am disabling it. The builds will be slower, but at
least will pass.
Checklist:
----------
Fixes request-yo-racks/docs#<issue_number>
=> Blow up the CircleCI cache

ryr-docs/docs/css/extra.css, ryr-docs/docs/guides/setup-full-environment.md, ryr-docs/docs/guides/update-branch.md, ryr-docs/docs/index.md, ryr-docs/mkdocs.yml
- New feature (non-breaking change which adds functionality)
Description
-----------
Customize the style of the site to make it look more like the Github
help site. It makes the steps clearer.
* Update the "Setting up a local environment" article
* Update the "Keeping your branch up-to-date " article
Ensure the instructions are clear for the contributors.
Checklist:
----------
Fixes request-yo-racks/docs#65
=> Improve the step style

ryr-docs/docs/contributor-zone/services-costs.md, ryr-docs/docs/index.md, ryr-docs/mkdocs.yml
Description
-----------
Adds an entry which explains which services the RYR projects use and the
cost associated to running the infrastructure.
Checklist:
----------
=> Add an article about the services and costs

ryr-docs/docs/contributor-zone/services-costs.md
Description
-----------
Fixes a typo in the services and costs entry.
Checklist:
----------
=> Fix a typo

ryr-docs/docs/guides/git-extras.md, ryr-docs/docs/guides/install-hub.md, ryr-docs/docs/guides/install-liquidprompt.md, ryr-docs/mkdocs.yml
Docs for productivity tools
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)
- Code cleanup / Refactoring
Description
-----------
Checklist:
----------
Fixes request-yo-racks/docs#<issue_number>
=> Guides for productivity tools.

ryr-docs/docs/guides/setup-full-environment.md
- Bug fix (non-breaking change which fixes an issue)
Description
-----------
The guide to help setting up a local environment was slightly outdated.
This patch fixes all the discrepancies.
Checklist:
----------
=> Update the local environment guide.

ryr-docs/docs/contributor-zone/goals-strategy.md, ryr-docs/docs/contributor-zone/ryr3.0-concepts.md, ryr-docs/docs/contributor-zone/services-costs.md, ryr-docs/mkdocs.yml
Description
-----------
Adds a page decribing the state we want to reach for each RYR project.
The subprojects also have their place on this page. This gives a clear
view of how we want to achieve rewriting the next RYR version.
Drive-bys:
* Fix typos
* Update services
Checklist:
----------
-  [X] I have updated the documentation accordingly
=> Add a page to document the RYR 3 concepts

ryr-docs/docs/contributor-zone/ryr3.0-concepts.md
Description
-----------
Adds more details to the projects mentioned on the concept page.
Checklist:
----------
-  [X] I have updated the documentation accordingly
=> Update the concept page

.github/PULL_REQUEST_TEMPLATE.md, ryr-docs/docs/learning/learning.md, ryr-docs/mkdocs.yml
Description
-----------
To help bring the contributor up to speed, this section compiles a set
of resources to learn the technologies that we use for the RYR projects.
Checklist:
----------
=> Add a learning section
